name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: cda43be9-21f9-4e4f-b547-25b1083ee0ef
          heroku_app_name: ctd-omega-editorial-prototype
          heroku_email: webmaster@nationalarchives.gov.uk
